# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://palatia.grad-rrnav.pub:8761/eureka
eureka.client.registryFetchIntervalSeconds=5
eureka.instance.preferIpAddress=false
eureka.instance.leaseRenewalIntervalInSeconds=10

# Spring-boot Admin Configuration
spring.boot.admin.client.url=http://palatia.grad-rrnav.pub:8761/admin

# Logging Configuration
logging.file.name=/var/log/${spring.application.name}.log
logging.file.max-size=10MB
logging.pattern.rolling-file-name=${spring.application.name}-%d{yyyy-MM-dd}.%i.log

# Management Endpoints
management.endpoint.logfile.external-file=/var/log/${spring.application.name}.log
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.trace.http.enabled=true

# Springdoc cconfiguration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.packagesToScan=org.grad.eNav.cKeeper.controllers

# Spring JPA Configuration - MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQL5Dialect
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true
spring.jpa.properties.hibernate.search.backend.directory.root=./lucene/
spring.jpa.properties.hibernate.search.schema_management.strategy=create-or-update
spring.jpa.properties.hibernate.search.backend.analysis.configurer=class:org.grad.eNav.cKeeper.config.CustomLuceneAnalysisConfigurer

# Datasource Configuration
spring.datasource.url=jdbc:mysql://atlas.grad-rrnav.pub:3306/c_keeper
spring.datasource.username=cKeeper
spring.datasource.password=1969VQcio9JcKPKx

# Keycloak Configuration
keycloak.enabled=true
spring.security.oauth2.client.registration.keycloak.client-id=c-keeper
spring.security.oauth2.client.registration.keycloak.client-secret=8b36b836-b4d7-4fc6-95d5-a402823f9a6b
spring.security.oauth2.client.registration.keycloak.client-name=Keycloak
spring.security.oauth2.client.registration.keycloak.provider=keycloak
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.scope=openid
spring.security.oauth2.client.registration.keycloak.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://palatia.grad-rrnav.pub:8090/realms/niord
spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://palatia.grad-rrnav.pub:8090/realms/niord

# Open the correct resources without authentication
gla.rad.ckeeper.resources.open:/,/index,/webjars/**,/css/**,/lib/**,/images/**,/src/**,/api/signatures/mmsi/verify/**

# Front-end Information
gla.rad.ckeeper.info.name=Certificate Keeper
gla.rad.ckeeper.info.version=0.0.1
gla.rad.ckeeper.info.operatorName=Research and Development Directorate of GLA of UK and Ireland
gla.rad.ckeeper.info.operatorContact=Nikolaos.Vastardis@gla-rad.org
gla.rad.ckeeper.info.operatorUrl=https://www.gla-rad.org/
gla.rad.ckeeper.info.copyright=\u00A9 2021 GLA Research & Development

# MCP Configuration
gla.rad.ckeeper.mcp.host=api-x509.maritimeconnectivity.net
gla.rad.ckeeper.mcp.organisation=grad
gla.rad.ckeeper.mcp.mcpOrgPrefix=urn:mrn:mcp:org:mcc
gla.rad.ckeeper.mcp.mcpEntityPrefix=urn:mrn:mcp
gla.rad.ckeeper.mcp.mcpEntitySuffix=mcc
gla.rad.ckeeper.mcp.keyStore=mcp/keystore.p12
gla.rad.ckeeper.mcp.keyStorePassword=I5-jxFaKysB&^-dZhrS&7BF5qr
gla.rad.ckeeper.mcp.keyStoreType=PKCS12
gla.rad.ckeeper.mcp.trustStore=mcp/truststore.p12
gla.rad.ckeeper.mcp.trustStorePassword=j8SyzZmydmv29nLh
gla.rad.ckeeper.mcp.trustStoreType=PKCS12
gla.rad.ckeeper.mcp.trustStore.rootCertificate.alias=mcp-root
gla.rad.ckeeper.mcp.trustStore.rootCertificate.thumbprintAlgorithm=SHA-1

# X509 Certificate Configuration
gla.rad.ckeeper.x509.keypair.curve=secp256r1
gla.rad.ckeeper.x509.cert.algorithm=SHA256withCVC-ECDSA
gla.rad.ckeeper.x509.cert.dirName=C = GB, O = urn:mrn:mcp:org:mcc:grad, OU = user, CN = Admin Admin, UID = urn:mrn:mcp:user:mcc:grad:admin, emailAddress = glaresearchdevelopment@gmail.com
gla.rad.ckeeper.x509.cert.yearDuration=1

