# Disable Security when local
keycloak.enabled=false

# Enable the local security
app.security.basic.enabled=true
spring.security.user.name=user
spring.security.user.password=password
spring.security.user.roles=user

# Disable Eureka when local
eureka.client.enabled=false

# Logging Configuration
logging.file.name=/var/log/${spring.application.name}.log
logging.file.max-size=10MB
logging.pattern.rolling-file-name=${spring.application.name}-%d{yyyy-MM-dd}.%i.log

# Springdoc cconfiguration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.packagesToScan=org.grad.eNav.cKeeper.controllers

# Spring JPA Configuration - MySQL
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true
spring.jpa.properties.hibernate.search.backend.directory.root=./lucene/
spring.jpa.properties.hibernate.search.schema_management.strategy=create-or-update
spring.jpa.properties.hibernate.search.backend.analysis.configurer=class:org.grad.eNav.cKeeper.config.CustomLuceneAnalysisConfigurer

# Datasource Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/c_keeper
spring.datasource.username=cKeeper
spring.datasource.password=1969VQcio9JcKPKx

# Open the correct resources without authentication
gla.rad.ckeeper.resources.open=/,/login,/index,/webjars/**,/css/**,/lib/**,/images/**,/src/**,/api/**

# Front-end Information
gla.rad.ckeeper.info.name=Certificate Keeper
gla.rad.ckeeper.info.version=0.0.3
gla.rad.ckeeper.info.operatorName=Research and Development Directorate of GLA of UK and Ireland
gla.rad.ckeeper.info.operatorContact=Nikolaos.Vastardis@gla-rad.org
gla.rad.ckeeper.info.operatorUrl=https://www.gla-rad.org/
gla.rad.ckeeper.info.copyright=\u00A9 2023 GLA Research & Development

# MCP Configuration
gla.rad.ckeeper.mcp.host=api-x509.maritimeconnectivity.net
gla.rad.ckeeper.mcp.organisation=grad
gla.rad.ckeeper.mcp.mcpOrgPrefix=urn:mrn:mcp:org:mcc
gla.rad.ckeeper.mcp.mcpEntityPrefix=urn:mrn:mcp
gla.rad.ckeeper.mcp.mcpEntitySuffix=mcc
gla.rad.ckeeper.mcp.keyStore=mcp/keystore.p12
gla.rad.ckeeper.mcp.keyStorePassword=I5-jxFaKysB&^-dZhrS&7BF5qr
gla.rad.ckeeper.mcp.keyStoreType=PKCS12
gla.rad.ckeeper.mcp.trustStore=mcp/truststore.p12
gla.rad.ckeeper.mcp.trustStorePassword=j8SyzZmydmv29nLh
gla.rad.ckeeper.mcp.trustStoreType=PKCS12
gla.rad.ckeeper.mcp.trustStore.rootCertificate.alias=mcp-root
gla.rad.ckeeper.mcp.trustStore.rootCertificate.thumbprintAlgorithm=SHA-1

# X509 Certificate Configuration
gla.rad.ckeeper.x509.keypair.curve=secp256r1
gla.rad.ckeeper.x509.cert.algorithm=SHA256withCVC-ECDSA
gla.rad.ckeeper.x509.cert.dirName=C = GB, O = urn:mrn:mcp:org:mcc:grad, OU = user, CN = Admin Admin, UID = urn:mrn:mcp:user:mcc:grad:admin, emailAddress = glaresearchdevelopment@gmail.com
gla.rad.ckeeper.x509.cert.yearDuration=1