# Disable Security when local
keycloak.enabled=false

# Enable the local security
app.security.basic.enabled=true
spring.security.user.name=user
spring.security.user.password=password

# Disable Eureka when local
eureka.client.enabled=false

# Datasource Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/c_keeper